import React from "react";
import { motion } from "framer-motion";
import { Button } from "./ui/button";

interface HeroSectionProps {
  onCtaClick?: () => void;
}

const HeroSection = ({
  onCtaClick = () =>
    window.scrollTo({ top: document.body.scrollHeight, behavior: "smooth" }),
}: HeroSectionProps) => {
  return (
    <section className="relative h-screen w-full overflow-hidden bg-[#111111]">
      {/* Background with parallax effect */}
      <div
        className="absolute inset-0 bg-cover bg-center bg-no-repeat"
        style={{
          backgroundColor: "#111111",
          transform: "translateZ(0)",
        }}
      >
        {/* Red abstract art background */}
        <div
          className="absolute inset-0 bg-cover bg-center bg-no-repeat"
          style={{
            backgroundImage:
              "url('/u3178933537_Full-page_scroll_website_concept_for_a_creative_A_992ff31d-756e-47b9-a27b-d8b6fd3342e3_0.png')",
            opacity: 0.9,
          }}
        />
      </div>

      {/* Content container */}
      <div className="container relative z-10 mx-auto flex h-full max-w-[1280px] flex-col items-start justify-center px-8 md:px-[120px]">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4 }}
          className="max-w-4xl"
        >
          {/* Main headline */}
          <h1 className="mb-6 font-sans text-4xl font-bold leading-tight tracking-tight text-white md:text-6xl lg:text-8xl">
            HIGH-QUALITY COMMERCIAL CONTENT / GENERATED BY AI. DELIVERED IN
            DAYS.
          </h1>

          {/* Subheading */}
          <p className="mb-8 text-lg text-white/80 md:text-2xl">
            От идеи — до ролика 4К и Instagram-профиля &lt; 5 дней.
          </p>

          {/* CTA Button */}
          <Button
            onClick={onCtaClick}
            className="bg-[#E30613] px-8 py-6 text-lg font-medium text-white hover:bg-[#E30613]/90"
          >
            Get concept in 24 h
          </Button>
        </motion.div>
      </div>

      {/* Scroll indicator */}
      <motion.div
        className="absolute bottom-8 left-1/2 -translate-x-1/2"
        animate={{ y: [0, 10, 0] }}
        transition={{ repeat: Infinity, duration: 1.5 }}
      >
        <div className="h-12 w-6 rounded-full border-2 border-white/30">
          <div className="mx-auto mt-2 h-2 w-2 rounded-full bg-white/50"></div>
        </div>
      </motion.div>
    </section>
  );
};

export default HeroSection;
